plugins {
    id 'java'
    id 'application'
}

group = 'net.foulest'
mainClassName = 'net.foulest.Main'
version = '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

dependencies {
    // Uncomment these when needed
    // implementation 'com.squareup.okhttp3:okhttp:4.9.1'
    // implementation 'com.google.code.gson:gson:2.8.9'
}
