plugins {
    id 'java'
    id 'application'
}

group 'net.foulest'
version '1.0.0'
compileJava.options.encoding = 'UTF-8'

repositories {
    mavenCentral()
}

dependencies {
    // Uncomment these when needed
    // implementation 'com.squareup.okhttp3:okhttp:4.9.1'
    // implementation 'com.google.code.gson:gson:2.8.9'
}

jar {
    manifest {
        attributes(
                'Main-Class': 'net.foulest.Main'
        )
    }
}
