name: Run Java Project

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '18.0.2'

      - name: Compile and Run Java Code
        run: |
          javac net/foulest/pokemon/Pokemon.java net/foulest/pokemon/data/Ability.java net/foulest/pokemon/data/HeldItem.java net/foulest/pokemon/data/Nature.java net/foulest/pokemon/data/Type.java net/foulest/Main.java
          java net.foulest.Main
